In [1]:
import torch
import torch.nn as nn

In [2]:
#Создание объекта нейросети
net = nn.Sequential(nn.Linear(700, 500), nn.ReLU(), nn.Linear(500, 200), nn.ReLU(), nn.Linear(200, 10))

In [3]:
net

Sequential(
  (0): Linear(in_features=700, out_features=500, bias=True)
  (1): ReLU()
  (2): Linear(in_features=500, out_features=200, bias=True)
  (3): ReLU()
  (4): Linear(in_features=200, out_features=10, bias=True)
)

In [4]:
#Точно также создадим сеть, но теперь слои имеют название

from collections import OrderedDict

net = nn.Sequential(
    OrderedDict(
        [
            ('linear1', nn.Linear(700, 500)),
            ('relu1', nn.ReLU()),
            ('linear2', nn.Linear(500, 200)),
            ('relu2', nn.ReLU()),
            ('linear3', nn.Linear(200, 10))
        ]
    )
)

In [6]:
#Можно получить доступ к любому слою сети, весам любого слоя и т.д.
net.linear1

Linear(in_features=700, out_features=500, bias=True)

In [7]:
#создадим какой-то входной тензор
input_tensor = torch.rand(10, 700)

net(input_tensor).shape

torch.Size([10, 10])

In [10]:
class CustomTaskNetwork(nn.Module):
    def __init__(self):
        super().__init__()

        self.linear1 = nn.Linear(700, 500)
        self.linear2 = nn.Linear(500, 200)
        self.linear3 = nn.Linear(200, 10)

        self.activations = nn.ReLU()

    def forward(self, x):
        output = self.activations(self.linear1(x))
        output = self.activations(self.linear2(output))
        output = self.linear3(output)

        return output

In [11]:
net = CustomTaskNetwork()
net(input_tensor).shape

torch.Size([10, 10])

In [12]:
#перемещение сети на гпу
#net.to()

In [13]:
#train - тренировка сети, вычисление градиентов и всё такое сякое
#евал - это работа сети в режиме предсказаний, градиенты не считаются в этот момент
net.train()
net.eval()
# заморозка части слоёв
net.requires_grad_()

CustomTaskNetwork(
  (linear1): Linear(in_features=700, out_features=500, bias=True)
  (linear2): Linear(in_features=500, out_features=200, bias=True)
  (linear3): Linear(in_features=200, out_features=10, bias=True)
  (activations): ReLU()
)

In [16]:
list(net.parameters())

[Parameter containing:
 tensor([[ 0.0170,  0.0038,  0.0080,  ...,  0.0301,  0.0309,  0.0088],
         [-0.0067, -0.0186, -0.0041,  ..., -0.0070,  0.0048,  0.0252],
         [-0.0266, -0.0003,  0.0043,  ..., -0.0192, -0.0318, -0.0190],
         ...,
         [ 0.0306, -0.0021,  0.0048,  ...,  0.0196,  0.0122, -0.0199],
         [-0.0158, -0.0084, -0.0276,  ..., -0.0262,  0.0265,  0.0018],
         [ 0.0040, -0.0247,  0.0376,  ...,  0.0128,  0.0102, -0.0139]],
        requires_grad=True),
 Parameter containing:
 tensor([ 1.2599e-02,  2.3634e-02,  3.1302e-03, -2.6670e-02,  9.1454e-03,
         -3.4555e-02,  1.2547e-02, -4.1844e-03,  2.7773e-02, -2.7672e-02,
          1.8957e-02, -1.4012e-03, -2.0991e-02,  7.3393e-03, -1.2401e-02,
         -8.5118e-03,  2.6291e-02, -2.6440e-02,  3.3514e-02, -2.4662e-02,
         -2.5853e-02,  1.4202e-02,  2.2114e-02,  9.1471e-03,  1.8276e-02,
          1.8183e-02, -3.0803e-02, -2.4727e-02, -3.4196e-02, -3.1766e-02,
         -3.6923e-02,  7.8870e-03,  2.30

In [17]:
#ордер дикт с параметрами сети
net.state_dict()

OrderedDict([('linear1.weight',
              tensor([[ 0.0170,  0.0038,  0.0080,  ...,  0.0301,  0.0309,  0.0088],
                      [-0.0067, -0.0186, -0.0041,  ..., -0.0070,  0.0048,  0.0252],
                      [-0.0266, -0.0003,  0.0043,  ..., -0.0192, -0.0318, -0.0190],
                      ...,
                      [ 0.0306, -0.0021,  0.0048,  ...,  0.0196,  0.0122, -0.0199],
                      [-0.0158, -0.0084, -0.0276,  ..., -0.0262,  0.0265,  0.0018],
                      [ 0.0040, -0.0247,  0.0376,  ...,  0.0128,  0.0102, -0.0139]])),
             ('linear1.bias',
              tensor([ 1.2599e-02,  2.3634e-02,  3.1302e-03, -2.6670e-02,  9.1454e-03,
                      -3.4555e-02,  1.2547e-02, -4.1844e-03,  2.7773e-02, -2.7672e-02,
                       1.8957e-02, -1.4012e-03, -2.0991e-02,  7.3393e-03, -1.2401e-02,
                      -8.5118e-03,  2.6291e-02, -2.6440e-02,  3.3514e-02, -2.4662e-02,
                      -2.5853e-02,  1.4202e-02,  2.2114e

In [18]:
net.load_state_dict(net.state_dict())

<All keys matched successfully>

Оптимизаторы

In [19]:
from torch import optim

In [20]:
optim.SGD, optim.Adam

(torch.optim.sgd.SGD, torch.optim.adam.Adam)

In [22]:
#передаем в оптимайзер параметры нашей сети и длину шага
optimizer = optim.Adam(net.parameters(), lr=0.0001)

In [23]:
optimizer

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: False
    lr: 0.0001
    maximize: False
    weight_decay: 0
)

In [24]:
#оптимизируем только первый и второй слой, при этом шаг на втором слое особый
optimizer = optim.SGD(
    [
        {"params": net.linear1.parameters()},
        {"params": net.linear2.parameters(), "lr": 1e-3}
    ],
    lr=1e-2,
    momentum=0.9
)

In [26]:
#делаем шаг оптимайзера
optimizer.step()

In [28]:
#после этого нужно обнулить градиенты
optimizer.zero_grad()

Функции потерь

In [30]:
nn.L1Loss, nn.MSELoss, nn.CrossEntropyLoss

(torch.nn.modules.loss.L1Loss,
 torch.nn.modules.loss.MSELoss,
 torch.nn.modules.loss.CrossEntropyLoss)

In [31]:
loss = nn.MSELoss()

In [32]:
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)

output = loss(input, target)

print(output)

output.backward()

tensor(1.9503, grad_fn=<MseLossBackward0>)


In [33]:
input.grad

tensor([[ 0.2655,  0.0821,  0.0948,  0.1920, -0.1090],
        [ 0.2002,  0.0061, -0.4460, -0.3261, -0.0722],
        [ 0.0716, -0.0791,  0.0780,  0.0192, -0.1291]])

Датасеты и даталоадеры

In [34]:
from torch.utils.data import Dataset
from torch.utils.data import TensorDataset

In [36]:
n_features = 2
n_objects = 300

In [37]:
w_true = torch.randn(n_features)
X = (torch.rand(n_objects, n_features) - 0.5) * 10
X *= (torch.arange(n_features) * 2 + 1)
Y = (X @ w_true + torch.randn(n_objects)).unsqueeze(1)

In [38]:
dataset = TensorDataset(X, Y)

In [39]:
dataset[0]

(tensor([ 0.6620, -3.8205]), tensor([2.3141]))

In [41]:
X[0]

tensor([ 0.6620, -3.8205])

In [42]:
class CustomDataset(Dataset):
    def __init__(self, w_true, n_features, n_objects):
        self.X = (torch.rand(n_objects, n_features) - 0.5) * 10
        self.X *= (torch.arange(n_features) * 2 + 1)
        self.Y = self.X @ w_true + torch.randn(n_objects)

    def __len__(self):
        return len(self.Y)
    def __getitem__(self, item):
        return self.Y[item], self.Y[item]

In [43]:
dataset = CustomDataset(w_true, n_features, n_objects)

In [44]:
dataset[0]

(tensor(4.0013), tensor(4.0013))

In [45]:
len(dataset)

300

In [46]:
from torch.utils.data import DataLoader

In [47]:
loader = DataLoader(dataset, batch_size=4, shuffle=True)

In [50]:
for x, y in loader:
    print(x.shape)

torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Size([4])
torch.Si

In [49]:
X.shape

torch.Size([300, 2])

Общая структура обученя модели

In [51]:
model.train()

for x, y in dataloader:
    optimizer.zero_grad()
    output = model(x)
    loss = loss_fn(output, y)
    loss.backward()
    optimizer.step()
#один проход по даталоадеру называется одной эпохой

NameError: name 'model' is not defined

In [52]:
#Обучение первой нейросети

In [53]:
class CustomTaskNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(n_features, 1)

    def forward(self, x):
        return self.linear(x)

net = CustomTaskNetwork()
optimizer = optim.Adam(net.parameters(), lr=1e-3)
loss_fn = nn.MSELoss()
dataset = TensorDataset(X, Y)
loader = DataLoader(dataset, batch_size=4, shuffle=True)
w_list = torch.empty(len(loader) + 1, n_features)

In [54]:
net.train()

for i, (x, y) in enumerate(loader):
    w_list[i] = net.linear.weight.detach().clone()
    optimizer.zero_grad()
    output = net(x)
    loss = loss_fn(output, y)
    print(f"MSE на шаге {i}{loss.item():.5f}")
    loss.backward()
    optimizer.step()
w_list[len(loader)] = net.linear.weight.detach().clone()

MSE на шаге 0217.99582
MSE на шаге 1126.96246
MSE на шаге 212.73696
MSE на шаге 3211.95782
MSE на шаге 4143.79070
MSE на шаге 551.79517
MSE на шаге 646.10628
MSE на шаге 7127.66228
MSE на шаге 865.56555
MSE на шаге 9225.13774
MSE на шаге 10144.68591
MSE на шаге 11167.69485
MSE на шаге 1298.50328
MSE на шаге 13260.62180
MSE на шаге 14127.47001
MSE на шаге 1589.41429
MSE на шаге 16103.75901
MSE на шаге 17157.29520
MSE на шаге 1852.60718
MSE на шаге 19110.64365
MSE на шаге 20153.16663
MSE на шаге 21113.24628
MSE на шаге 22159.59294
MSE на шаге 2383.95333
MSE на шаге 2430.33527
MSE на шаге 25135.09601
MSE на шаге 26182.72141
MSE на шаге 2739.79673
MSE на шаге 28118.58049
MSE на шаге 2971.92991
MSE на шаге 30154.70557
MSE на шаге 31154.95154
MSE на шаге 32103.77626
MSE на шаге 33161.37579
MSE на шаге 34104.29935
MSE на шаге 3598.15703
MSE на шаге 3624.29409
MSE на шаге 37128.90590
MSE на шаге 38102.43903
MSE на шаге 3986.79538
MSE на шаге 40139.18016
MSE на шаге 41244.20355
MSE на шаге 4213

In [7]:
import numpy as np
import pandas as pd


CON = "postgresql://robot-startml-ro:pheiph0hahj1Vaif@postgres.lab.karpov.courses:6432/startml"


def select(query: str) -> pd.DataFrame:
    global CON
    return pd.read_sql(query, CON)


q = """
SELECT fa.post_id,
       fa.time,
       u.age,
       u.os
FROM   feed_action AS fa
       JOIN "user" AS u
         ON u.id = fa.user_id
WHERE  u.city = 'Omsk'
       AND
       fa.action = 'like'
ORDER  BY fa.time DESC
LIMIT  100
"""

result = select(q)
result.to_csv("Python_HW_6_Task_15.csv", sep=",", index=False)

AttributeError: 'OptionEngine' object has no attribute 'execute'